name: Fileset credential vending integration test

# Controls when the workflow will run
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Integration test for AMD64 architecture
  test-amd64-arch:
    runs-on: ubuntu-latest
    env:
      S3_STS_ACCESS_KEY_ID: ${{ secrets.S3_STS_ACCESS_KEY_ID }}
      S3_STS_SECRET_ACCESS_KEY: ${{ secrets.S3_STS_SECRET_ACCESS_KEY }}
      S3_STS_ENDPOINT: http://s3.ap-northeast-1.amazonaws.com
      S3_STS_BUCKET_NAME: sts-test-bucket-001
      S3_STS_REGION: ap-northeast-1
      S3_STS_ROLE_ARN: arn:aws:iam::730335553010:role/sts_s3_access_role
      S3_ACCESS_KEY_ID: ${{ secrets.S3_STS_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_STS_SECRET_ACCESS_KEY }}
      S3_ENDPOINT: http://s3.ap-northeast-1.amazonaws.com
      S3_BUCKET_NAME: sts-test-bucket-001
      PLATFORM: ${{ matrix.architecture }}
      S3_ACCESS_KEY_ID_FOR_CREDENTIAL: ${{ secrets.S3_STS_ACCESS_KEY_ID }}
      S3_BUCKET_NAME_FOR_CREDENTIAL: sts-test-bucket-001
      S3_ENDPOINT_FOR_CREDENTIAL: http://s3.ap-northeast-1.amazonaws.com
      S3_REGION_FOR_CREDENTIAL: ap-northeast-1
      S3_ROLE_ARN_FOR_CREDENTIAL: arn:aws:iam::730335553010:role/sts_s3_access_role
      S3_SECRET_ACCESS_KEY_FOR_CREDENTIAL: ${{ secrets.S3_STS_SECRET_ACCESS_KEY }}
    timeout-minutes: 45
    strategy:
      matrix:
        architecture: [linux/amd64]
        java-version: [ 17 ]
        test-mode: [ deploy ]
        backend: [ mysql ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Check required command
        run: |
          gravitino-oss/dev/ci/check_commands.sh
      - name: Fileset Credential Vending Integration Test
        id: integrationTest
        run: |
          ./gradlew -p gravitino-oss build -x test -x clients:client-python:build
          mkdir -p /tmp/bundles
          cp -r gravitino-oss/bundles/*-bundle/build/libs/*.jar /tmp/bundles
          ./gradlew compileDistribution -x test -PjdkVersion=${{ matrix.java-version }}
          cp -r -f ./distribution ./gravitino-oss
          cp -r /tmp/bundles/* ./gravitino-oss/distribution/package/catalogs/fileset/libs
          ./gradlew -p gravitino-oss -PskipTests -PtestMode=${{ matrix.test-mode }} -PjdkVersion=${{ matrix.java-version }} -PjdbcBackend=${{ matrix.backend }} -PskipDockerTests=false :clients:filesystem-hadoop3:test --tests "org.apache.gravitino.filesystem.hadoop.integration.test.GravitinoVirtualFileSystemS3CredentialIT"
          ./gradlew -p gravitino-oss -PskipTests -PjdkVersion=${{ matrix.java-version }} -PpythonVersion=3.8 -PskipDockerTests=false :clients:client-python:test
      - name: Upload integrate tests reports
        uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.integrationTest.outcome == 'failure' }}
        with:
          name: integrate test reports-${{ matrix.java-version }}-${{ matrix.test-mode }}-${{ matrix.backend }}
          path: |
            gravitino-oss/build/reports
            gravitino-oss/iceberg/iceberg-rest-server/build/*.log
            gravitino-oss/integration-test/build/*.log
            gravitino-oss/integration-test/build/*.tar
            gravitino-oss/integration-test/build/trino-ci-container-log/hive/*.*
            gravitino-oss/integration-test/build/trino-ci-container-log/hdfs/*.*
            gravitino-oss/distribution/package/logs/*.out
            gravitino-oss/distribution/package/logs/*.log
            gravitino-oss/catalogs/**/*.log
            gravitino-oss/catalogs/**/*.tar
            gravitino-oss/distribution/**/*.log